### ISSUE TITLE
Stock data limited to one month back?

### ISSUE THREAD

**Issue by JaphyR** [joqueka/bf4py#2]
Hey,
thx 4 your effort, been long looking for a Xetra equivalent of yfinance.
I tried your OHLC script, but it seems there's no way to get quotes further than one month back (I tried with that days=365 example).
Is there any limitation at API level?

**Comment by joqueka** [comment]
Hi :)
there are indeed some server side limitations. These are either limits in history or limits in the amount of data you can load. Regarding the first point I recommend you to have a look at the website of www.boerse-frankfurt.de and check how much history you can get there. Everything you can see there can be read by bf4py. 
For dealing with the download limits I implemented loops where I found them to be needed. Since there's no official API documentation it's based on try-and-error.
If you still have struggles, please provide some more details that I can retrace possible errors.

**Comment by bodober** [comment]
Hi, 
it seems like I am having the same issue. No matter what timeframe I put I only receive the last 20 days back. Any idea how to correct this behavior?

Thank you for your efforts! Here an example which returns only the OHLC from the last 20 days. I checked on [www.boerse-frankfurt.de](http://www.boerse-frankfurt.de/) and the whole year is available.

  `


    import bf4py
    from datetime import datetime, timedelta
    import pandas as pd

    TickersOut= '.\Screener\Tickers.csv'
    df = pd.read_csv(TickersOut)
    
    isin_list = ['DE0006452907']
    
    skipped = 0
    
    for isin in isin_list:
            
    try:
        bf4py.general.data_sheet_header(isin)
    
        end_date = datetime.today()
        start_date = end_date - timedelta(days=365)
        
        history = bf4py.general.eod_data(isin, start_date, end_date)
        
        history_df = pd.DataFrame(history)
        history_df.to_csv('.\History\\' + isin + '.txt', index = False)
        
    except :
        skipped += 1
        
`

**Comment by joqueka** [comment]
Hi,
thanks for the hint. I finally found a parameter that limited the number of output records when not set. Should work now :)

Cheers

**Comment by bodober** [comment]
Thanks it works. Great job!
