### ISSUE TITLE
Real Time Data

### ISSUE THREAD

**Issue by schlummer13** [joqueka/bf4py#3]
Hey, 
What about this endpoint?

"https://api.boerse-frankfurt.de/v1/data/quote_box?isin={ISIN}&mic={XSC}".

I found nothing like this in your Script, but i want realtime data :D

**Comment by joqueka** [comment]
Hi,
thanks for the hint. I had a look at these endpoints at the beginning, but since the data is usually delayed by 15 minutes they are not really "realtime" and I considered them not much advantageous ;) However I will have a look at it as soon as I get to and see what I can do because these endpoints need a different approach since they need a streaming client.

**Comment by schlummer13** [comment]
This single entpoint don't need streaming. Try this :D Am 10.05.2022 13:56 schrieb joqueka ***@***.***>:
Hi,
thanks for the hint. I had a look at these endpoints at the beginning, but since the data is usually delayed by 15 minutes they are not really "realtime" and I considered them not much advantageous ;) However I will have a look at it as soon as I get to and see what I can do because these endpoints need a different approach since they need a streaming client.

**Comment by joqueka** [comment]
Hi,
as mentioned this and some others are streaming endpoints. And they only send data during trading hours what limits my development possibilities because this is not possible in the evenings. However I'll see what I can do to make getting this live data as easy as possible. Using the regular internal functions does not work out. Please be patient.

**Comment by joqueka** [comment]
Hi,
finally I added support for streaming of live data :)
Using one of the three new functions in bf4py.live_data will return an object which is able to stream data in a background process and can send the data to a function of your choice.

Have fun!
